import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "@/app/assets/Logo";
import Keyboard from "@/app/assets/Keyboard";
import Crown from "@/app/assets/Crown";
import Setting from "@/app/assets/Setting";
import Bell from "@/app/assets/Bell";
import User from "@/app/assets/User";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-color1 text-color5 p-4`}>
        <header className="flex justify-start items-center gap-3 my-5 px-36">
          <Logo />
          <h1 className="font-semibold text-4xl text-color5">monkeytype</h1>

          <div className="flex gap-3 px-2 *:transition-colors *:duration-300 *:cursor-pointer grow">
            <Keyboard />
            <Crown />
            <Setting />
          </div>

          <div className="flex gap-3 px-2 *:transition-colors *:duration-300 *:cursor-pointer">
            <Bell />
            <User />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
